apiVersion: v2
name: gh-tracker-service
description: Helm chart for GitHub Activity Tracker backend service
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
maintainers:
  - email: info@mosip.io
    name: MOSIP
