{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexus-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "nexus-server.labels" (dict "name" "nexus-api" "ctx" $) | nindent 4 }}
  annotations: {{- include "nexus-server.annotations" (dict "ctx" $) | nindent 4 }}
{{- end }}
