apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-ui
  namespace: {{ .Values.namespace }}
  labels: {{- include "nexus-ui.labels" . | nindent 4 }}
  annotations: {{- include "nexus-ui.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "nexus-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "nexus-ui.labels" . | nindent 8 }}
        {{- $extraPodLabels := omit (.Values.podLabels | default dict) "app" }}
        {{- if $extraPodLabels }}
        {{- toYaml $extraPodLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nexus-ui.serviceAccountName" . }}
      {{- include "nexus-ui.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: nexus-ui
          image: {{ include "nexus-ui.image" . }}
          imagePullPolicy: {{ include "nexus-ui.imagePullPolicy" . }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{- if or .Values.extraEnvVars .Values.extraEnvVarsCM .Values.extraEnvVarsSecret }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            {{- range .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
