{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexus-ui.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "nexus-ui.labels" . | nindent 4 }}
  annotations: {{- include "nexus-ui.annotations" . | nindent 4 }}
{{- end }}
